# Project: hw22
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = hw22.o
LINKOBJ  = hw22.o
LIBS     = -L"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/©v¦ö/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = hw22.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

hw22.o: hw22.cpp
	$(CC) -c hw22.cpp -o hw22.o $(CFLAGS)
